apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: base
    releaseName: istio-base
    version: 1.21.1
    repo: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system
    includeCRDs: true

  - name: istiod
    releaseName: istiod
    version: 1.21.1
    repo: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system
    includeCRDs: true
