apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-demo

resources:
  # step 1: 50% traffic shift to v3
  # - virtual-service-reviews-50-v3.yaml
  # step 2: 100% traffic shift to v3
  - virtual-service-reviews-v3.yaml
