apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gateway
    releaseName: istio-ingress
    version: 1.21.1
    repo: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system
    includeCRDs: true
